-- ============================================================================
-- 0016_sys_audit_log.sql
-- 审计日志表:记录用户操作的关键信息,供合规/排错追溯
-- ============================================================================

create table if not exists sys.sys_audit_log (
    id            bigint generated by default as identity primary key,
    trace_id      text,
    user_id       bigint,
    login_name    text,
    http_method   text not null,
    http_path     text not null,
    http_status   int,
    module        text,
    action        text,
    target_type   text,
    target_id     bigint,
    ip            text,
    user_agent    text,
    request_body  jsonb,
    response_code int,
    duration_ms   int,
    extra_json    jsonb not null default '{}'::jsonb,
    created_at    timestamp not null default now()
);

-- 常用查询索引
create index if not exists idx_audit_user_time
    on sys.sys_audit_log(user_id, created_at desc);
create index if not exists idx_audit_trace
    on sys.sys_audit_log(trace_id)
    where trace_id is not null;
create index if not exists idx_audit_path_time
    on sys.sys_audit_log(http_path, created_at desc);
create index if not exists idx_audit_target
    on sys.sys_audit_log(target_type, target_id)
    where target_type is not null;

-- 追踪时间范围的 BRIN 索引(时间是单调的,BRIN 很省)
create index if not exists brin_audit_created
    on sys.sys_audit_log using brin (created_at);

comment on table sys.sys_audit_log is '审计日志:每次受保护请求记录一行';
comment on column sys.sys_audit_log.trace_id is '与 tracing span trace_id 对齐,排错关联';
comment on column sys.sys_audit_log.duration_ms is '请求处理耗时(毫秒)';
comment on column sys.sys_audit_log.request_body is '仅对关键敏感操作记录;默认空';
