-- ============================================================================
-- 0018_multi_tenancy.sql
-- 多租户:引入 tenant_id,老数据默认租户 1
-- ============================================================================

-- 1. 租户主表 -----------------------------------------------------------------
create table if not exists sys.sys_tenant (
    id             bigint generated by default as identity primary key,
    tenant_code    text not null unique,
    tenant_name    text not null,
    is_active      boolean not null default true,
    extra_json     jsonb not null default '{}'::jsonb,
    created_at     timestamp not null default now(),
    updated_at     timestamp not null default now()
);

insert into sys.sys_tenant (id, tenant_code, tenant_name)
values (1, 'DEFAULT', '默认租户')
on conflict (id) do nothing;

comment on table sys.sys_tenant is '租户(多公司/多工厂隔离的最小单位)';

-- 2. 给所有业务表加 tenant_id,默认 1(单值回填)---------------------------
do $$
declare
    tbl record;
begin
    for tbl in
        select schemaname, tablename
          from pg_tables
         where schemaname in ('mdm', 'inv', 'wms', 'sys')
           and tablename not in ('sys_tenant', 'sys_audit_log', 'sys_jwt_revocation')
    loop
        execute format(
            'alter table %I.%I add column if not exists tenant_id bigint not null default 1',
            tbl.schemaname, tbl.tablename
        );
    end loop;
end $$;

-- 3. 给热点表建 tenant 复合索引(最常过滤的维度)-----------------------------
create index if not exists idx_inv_balance_tenant
    on wms.wms_inventory_balance(tenant_id, wh_id, loc_id, material_id);
create index if not exists idx_inv_txn_h_tenant
    on wms.wms_inventory_txn_h(tenant_id, created_at desc);
create index if not exists idx_wms_inbound_h_tenant
    on wms.wms_inbound_h(tenant_id, inbound_date desc);
create index if not exists idx_wms_outbound_h_tenant
    on wms.wms_outbound_h(tenant_id, outbound_date desc);
create index if not exists idx_wms_preissue_h_tenant
    on wms.wms_preissue_h(tenant_id, issue_date desc);
create index if not exists idx_mdm_material_tenant
    on mdm.mdm_material(tenant_id, material_code);
create index if not exists idx_mdm_warehouse_tenant
    on mdm.mdm_warehouse(tenant_id, wh_code);
create index if not exists idx_sys_user_tenant
    on sys.sys_user(tenant_id, login_name);

-- 4. 唯一约束追加 tenant 维度(避免跨租户冲突)-------------------------------
-- 注:老约束保留;新业务用 (tenant_id, xxx_code) 做逻辑唯一
create unique index if not exists uq_mdm_material_tenant_code
    on mdm.mdm_material(tenant_id, material_code);
create unique index if not exists uq_mdm_warehouse_tenant_code
    on mdm.mdm_warehouse(tenant_id, wh_code);
create unique index if not exists uq_sys_user_tenant_login
    on sys.sys_user(tenant_id, login_name);

-- 5. 审计表 / 黑名单也加 tenant_id(跨租户共享但可过滤)----------------------
alter table sys.sys_audit_log       add column if not exists tenant_id bigint;
alter table sys.sys_jwt_revocation  add column if not exists tenant_id bigint;
create index if not exists idx_audit_tenant_time
    on sys.sys_audit_log(tenant_id, created_at desc)
    where tenant_id is not null;

-- 6. 多租户下删掉单列 login_name 唯一约束 -------------------------------------
-- 老表定义:login_name varchar(100) not null unique
-- 默认约束名 sys_user_login_name_key(若自定义过需调整)
alter table sys.sys_user drop constraint if exists sys_user_login_name_key;

-- material_code / wh_code 同理,0018 已建 (tenant_id,xxx) 唯一索引作为代替
alter table mdm.mdm_material  drop constraint if exists mdm_material_material_code_key;
alter table mdm.mdm_warehouse drop constraint if exists mdm_warehouse_wh_code_key;
