-- ============================================================================
-- 0019_scheduler.sql
-- 异步任务调度器:执行记录 + leader advisory lock key
-- ============================================================================

create table if not exists sys.sys_scheduled_job_log (
    id            bigint generated by default as identity primary key,
    job_name      text not null,
    started_at    timestamp not null default now(),
    finished_at   timestamp,
    status        text not null default 'RUNNING',  -- RUNNING / OK / FAIL / SKIPPED
    result_json   jsonb not null default '{}'::jsonb,
    error_message text,
    host          text,                             -- 执行实例标识
    duration_ms   int
);

create index if not exists idx_sched_log_name_time
    on sys.sys_scheduled_job_log(job_name, started_at desc);
create index if not exists idx_sched_log_status
    on sys.sys_scheduled_job_log(status, started_at desc)
    where status in ('FAIL', 'RUNNING');

comment on table sys.sys_scheduled_job_log is '调度任务执行记录';
comment on column sys.sys_scheduled_job_log.status is 'RUNNING / OK / FAIL / SKIPPED(被 leader 锁跳过)';

-- ----------------------------------------------------------------------------
-- preissue 超期字段(调度器会写)
-- 若 0006_wms_exceptions 未定义,这里补上
-- ----------------------------------------------------------------------------
alter table wms.wms_preissue_h add column if not exists timeout_flag boolean not null default false;
alter table wms.wms_preissue_h add column if not exists timeout_at   timestamp;

create index if not exists idx_preissue_timeout
    on wms.wms_preissue_h(timeout_flag, expected_close_date)
    where exception_status in ('PENDING', 'PARTIAL');

-- ----------------------------------------------------------------------------
-- 审计日志归档表(调度器每月把 90 天前的数据搬过来)
-- ----------------------------------------------------------------------------
create table if not exists sys.sys_audit_log_archive (
    like sys.sys_audit_log including all
);

comment on table sys.sys_audit_log_archive is '审计日志归档(≥ 90 天)';
