-- ============================================================================
-- 0020_domain_events.sql
-- 领域事件表(事件溯源 + outbox)
--
-- 策略:
--  - 所有业务状态变更(库存事务提交、单据状态转换)都写一条事件
--  - 写事件和业务表必须在同一 DB 事务中,保证原子性
--  - 事件一旦写入就不可变
--  - 后续 M7 接 Kafka/Pulsar 时,publisher 扫未 published 的事件往外推
-- ============================================================================

create schema if not exists events;

create table if not exists events.domain_event (
    id             bigint generated by default as identity primary key,
    tenant_id      bigint not null default 1,
    event_id       uuid not null default gen_random_uuid(),
    aggregate_type text not null,   -- 例:Inventory / Inbound / Outbound / Preissue ...
    aggregate_id   bigint,          -- 聚合根 id(txn_id / inbound_id / ...)
    event_type     text not null,   -- 例:InventoryTxnCommitted / InboundSubmitted
    event_version  int not null default 1,
    payload        jsonb not null,
    occurred_at    timestamp not null default now(),
    trace_id       text,
    actor_id       bigint,
    actor_name     text,
    -- outbox: publisher 扫 published = false 往外推
    published      boolean not null default false,
    published_at   timestamp
);

-- 保证 event_id 全局唯一(跨实例)
create unique index if not exists uq_domain_event_event_id
    on events.domain_event(event_id);

-- 常用查询索引
create index if not exists idx_domain_event_aggregate
    on events.domain_event(aggregate_type, aggregate_id, occurred_at desc);
create index if not exists idx_domain_event_tenant_time
    on events.domain_event(tenant_id, occurred_at desc);
create index if not exists idx_domain_event_type_time
    on events.domain_event(event_type, occurred_at desc);

-- outbox 查询:未 publish 且按时间顺序
create index if not exists idx_domain_event_outbox
    on events.domain_event(occurred_at)
    where published = false;

-- 时间范围查询:BRIN 省空间
create index if not exists brin_domain_event_time
    on events.domain_event using brin (occurred_at);

comment on table events.domain_event is '领域事件(事件溯源 + outbox 来源)';
comment on column events.domain_event.aggregate_type is '聚合根类型:Inventory / Inbound / Outbound / ...';
comment on column events.domain_event.event_type is '事件类型:InventoryTxnCommitted / InboundSubmitted / ...';
comment on column events.domain_event.published is 'outbox 标志:false = 未推送到事件总线';

-- gen_random_uuid() 在 pg 13+ 默认可用(pgcrypto 内置)。若部署版本较老,
-- 需在初始化时 `create extension if not exists pgcrypto;`
do $$
begin
    create extension if not exists pgcrypto;
exception when insufficient_privilege then
    -- 没权限装扩展也不 block;本 migration 允许跳过
    raise notice 'skipped pgcrypto extension';
end $$;
