apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cuba-ims.fullname" . }}-secret
  labels:
    {{- include "cuba-ims.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secrets.databaseUrl | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
